# Bot Configuration

## Member ID's for operators
member_id:              
  - id_1
  - id_2
  - id_3

oauth_access_token:   xoxp-
bot_user_oauth_token: xoxb-

# Must be seperated by dashes with no integers
channel_prefix:       sierra-hotel-